# Generated by Django 2.2.2 on 2019-07-01 21:25

import common.outils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Personne')),
                ('matricule', models.CharField(max_length=10, unique=True)),
                ('promotion', models.CharField(max_length=12, verbose_name='Promotion')),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Classe', verbose_name='Niveau')),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Filiere', verbose_name='Filière')),
            ],
            bases=('common.personne',),
        ),
        migrations.CreateModel(
            name='InfoSup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.ImageField(blank=True, null=True, upload_to=common.outils.chemin_sauvegarde_rapport, verbose_name="Photo d'identité")),
                ('emplois', models.CharField(blank=True, max_length=200, null=True)),
                ('compte_facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('compte_twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('compte_linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, verbose_name='Thème')),
                ('domaine_metier', models.CharField(max_length=200, verbose_name='Domaine métier')),
                ('resume', models.TextField(verbose_name='Résumé')),
                ('mots_cles', models.CharField(blank=True, max_length=200, verbose_name='Mots clés')),
                ('fichier_rapport', models.FileField(upload_to=common.outils.chemin_sauvegarde_rapport, verbose_name='Votre rapport de stage (pdf)')),
                ('date_premier_chargement', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.CharField(max_length=12, verbose_name='Année académique')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='depot_rapport.Etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu_stage', models.CharField(max_length=100, verbose_name="Structure d'accueil")),
                ('date_debut', models.DateField(verbose_name='Stage début le')),
                ('etat_stage', models.CharField(choices=[('Débuté', 'Débuté'), ('Encours', 'Encours'), ('Non trouvés', 'Non trouvé'), ('Fini', 'Fini')], max_length=20, verbose_name="État d'avancement")),
                ('superviseur_stage', models.CharField(max_length=200, verbose_name='Superviseur')),
                ('maitre_stage', models.CharField(max_length=200, verbose_name='Maître de Stage')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='depot_rapport.Etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prevue', models.DateField(verbose_name='Date de Soutenance')),
                ('date_effective', models.DateField(blank=True, null=True, verbose_name='Date effective')),
                ('heure', models.TimeField(null=True, verbose_name='Heure de soutenance')),
                ('salle', models.CharField(max_length=50)),
                ('note', models.IntegerField(null=True)),
                ('jury', models.CharField(max_length=200, null=True)),
                ('pv', models.CharField(max_length=200, null=True, verbose_name='Procès verbal')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='depot_rapport.Etudiant')),
                ('rapport', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='depot_rapport.Rapport')),
                ('stage', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='depot_rapport.Stage')),
            ],
        ),
        migrations.AddField(
            model_name='rapport',
            name='stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='depot_rapport.Stage'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='infosup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot_rapport.InfoSup', verbose_name='Informations suplémentaires'),
        ),
    ]
