# Generated by Django 2.1.3 on 2018-12-09 20:10

import common.outils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Personne')),
                ('matricule', models.CharField(max_length=10, unique=True)),
                ('promotion', models.CharField(max_length=12, verbose_name='Promotion')),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Filiere', verbose_name='Filière')),
                ('niveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Classe')),
            ],
            bases=('common.personne',),
        ),
        migrations.CreateModel(
            name='FichierRapport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('fichier_rapport', models.FileField(upload_to=common.outils.chemin_sauvegarde_rapport, verbose_name='Votre rapport de stage (pdf)')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, verbose_name='Thème')),
                ('domaine_metier', models.CharField(default='0', max_length=200, verbose_name='Domaine métier')),
                ('resume', models.TextField(verbose_name='Résumé')),
                ('motsCle', models.CharField(blank=True, max_length=200, verbose_name='Mots clés')),
                ('date_premierChargement', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.CharField(max_length=12, verbose_name='Année académique')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='depot_rapport.Etudiant')),
                ('f_rapport', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='depot_rapport.FichierRapport', verbose_name='Rapport de stage')),
            ],
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePrevu', models.DateField(verbose_name='Date de Soutenance')),
                ('dateEffective', models.DateField(blank=True, null=True, verbose_name='Date effective')),
                ('heure', models.TimeField(null=True, verbose_name='Heure de soutenance')),
                ('salle', models.CharField(max_length=50)),
                ('note', models.IntegerField(null=True)),
                ('jury', models.CharField(max_length=200, null=True)),
                ('pv', models.CharField(max_length=200, null=True, verbose_name='Procès verbal')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='depot_rapport.Etudiant')),
                ('rapport', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='depot_rapport.Rapport')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=100, verbose_name="Structure d'accueil")),
                ('dateDebut', models.DateField(verbose_name='Stage début le')),
                ('etat', models.CharField(choices=[('Débuté', 'Débuté'), ('Encours', 'Encours'), ('Non trouvés', 'Non trouvé'), ('Fini', 'Fini')], max_length=20, verbose_name="État d'avancement")),
                ('superviseur', models.CharField(max_length=200, verbose_name='Superviseur')),
                ('maitreStage', models.CharField(max_length=200, verbose_name='Maître de Stage')),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='depot_rapport.Etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='soutenance',
            name='stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='depot_rapport.Stage'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='depot_rapport.Stage'),
        ),
    ]
