# Generated by Django 2.1.3 on 2018-12-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot_rapport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapport',
            name='f_rapport',
        ),
        migrations.AddField(
            model_name='rapport',
            name='fichier_rapport',
            field=models.FileField(default='0', upload_to='', verbose_name='Votre rapport de stage (pdf)'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='FichierRapport',
        ),
    ]
