# Generated by Django 2.1.3 on 2018-12-09 22:33

import common.outils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depot_rapport', '0003_auto_20181209_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='fichier_rapport',
            field=models.FileField(upload_to=common.outils.chemin_sauvegarde_rapport, verbose_name='Votre rapport de stage (pdf)'),
        ),
    ]
