# Generated by Django 2.0.4 on 2018-05-12 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_classe', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('dPassword', models.CharField(max_length=30)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dpt', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_filiere', models.CharField(max_length=50)),
                ('dpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rapport.Departement')),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('numTel', models.CharField(max_length=25, null=True, unique=True)),
                ('sexe', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], default='H', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200)),
                ('resume', models.TextField()),
                ('fichier', models.FileField(upload_to='')),
                ('dateEnvoi', models.DateTimeField(auto_now_add=True)),
                ('dateModif', models.DateTimeField(auto_now=True)),
                ('anneAcademique', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datePrevu', models.DateField()),
                ('dateEffectif', models.DateField()),
                ('salle', models.CharField(max_length=50)),
                ('note', models.IntegerField()),
                ('jury', models.CharField(max_length=200)),
                ('pv', models.CharField(max_length=200)),
                ('rapport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Rapport.Rapport')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lieu', models.CharField(max_length=100)),
                ('etat', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UFR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ufr', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Rapport.Personne')),
                ('dateNaissance', models.DateField()),
                ('matricule', models.CharField(max_length=10, unique=True)),
                ('promotion', models.CharField(max_length=20)),
                ('filiere', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Filiere')),
                ('niveau', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Classe')),
            ],
            bases=('Rapport.personne',),
        ),
        migrations.CreateModel(
            name='MaitreStage',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Rapport.Personne')),
                ('profession', models.CharField(max_length=50)),
                ('employeur', models.CharField(max_length=100)),
            ],
            bases=('Rapport.personne',),
        ),
        migrations.CreateModel(
            name='Supersiveur',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Rapport.Personne')),
                ('titre', models.CharField(max_length=20)),
            ],
            bases=('Rapport.personne',),
        ),
        migrations.AddField(
            model_name='rapport',
            name='stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Rapport.Stage'),
        ),
        migrations.AddField(
            model_name='departement',
            name='ufr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rapport.UFR'),
        ),
        migrations.AddField(
            model_name='stage',
            name='maitreStage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.MaitreStage'),
        ),
        migrations.AddField(
            model_name='stage',
            name='stagiaire',
            field=models.ManyToManyField(to='Rapport.Etudiant'),
        ),
        migrations.AddField(
            model_name='stage',
            name='superviseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Supersiveur'),
        ),
        migrations.AddField(
            model_name='soutenance',
            name='etudiants',
            field=models.ManyToManyField(to='Rapport.Etudiant'),
        ),
        migrations.AddField(
            model_name='rapport',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rapport.Etudiant'),
        ),
        migrations.AddField(
            model_name='compte',
            name='proprietaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Rapport.Etudiant'),
        ),
    ]
