# Generated by Django 2.0.4 on 2018-05-28 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0002_auto_20180518_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='soutenance',
            name='heure',
            field=models.TimeField(null=True, verbose_name='Heure de soutenance'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='maitreStage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.MaitreStage', verbose_name='Maître de Stage'),
        ),
    ]
