# Generated by Django 2.0.4 on 2018-05-31 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0005_auto_20180528_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='dPassword',
        ),
    ]
