# Generated by Django 2.0.4 on 2018-06-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0006_remove_compte_dpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
