# Generated by Django 2.0.4 on 2018-06-01 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0007_auto_20180601_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo', models.CharField(max_length=11, verbose_name='Promtion')),
            ],
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Promotion', verbose_name='Promtion'),
        ),
    ]
