# Generated by Django 2.0.4 on 2018-06-01 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0008_auto_20180601_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='anneAcademique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Promotion', verbose_name='Année académique'),
        ),
    ]
