# Generated by Django 2.0.4 on 2018-06-01 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0009_auto_20180601_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapport',
            old_name='anneAcademique',
            new_name='anneeAcademique',
        ),
    ]
