# Generated by Django 2.0.4 on 2018-06-05 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0010_auto_20180601_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soutenance',
            name='etudiants',
        ),
        migrations.AddField(
            model_name='soutenance',
            name='etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Etudiant'),
        ),
        migrations.AddField(
            model_name='soutenance',
            name='stage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Stage'),
        ),
        migrations.AlterField(
            model_name='compte',
            name='proprietaire',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Etudiant'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='ufr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.UFR'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Promotion', verbose_name='Promotion'),
        ),
        migrations.AlterField(
            model_name='filiere',
            name='dpt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Departement'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Etudiant'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='fichier',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='stage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Stage'),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='rapport',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Rapport'),
        ),
        migrations.RemoveField(
            model_name='stage',
            name='stagiaire',
        ),
        migrations.AddField(
            model_name='stage',
            name='stagiaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Etudiant'),
        ),
    ]
