# Generated by Django 2.0.4 on 2018-06-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0011_auto_20180605_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='etat',
            field=models.CharField(choices=[('Pas encore trouvé', 'Pas encore trouvé'), ('Débuté', 'Débuté'), ('Encours', 'Encours'), ('Non trouves', 'Non trouvé')], max_length=20, verbose_name='État'),
        ),
    ]
