# Generated by Django 2.0.4 on 2018-06-06 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0012_auto_20180606_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Stage'),
        ),
    ]
