# Generated by Django 2.0.4 on 2018-06-13 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0013_auto_20180606_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7)),
                ('credits', models.IntegerField(max_length=2, verbose_name='Crédits')),
                ('nom_matiere', models.CharField(max_length=30, verbose_name='Nom de la matière')),
                ('niveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='UniteEnseignement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_unite', models.CharField(max_length=30, verbose_name="Unité d'enseignement")),
            ],
        ),
        migrations.AddField(
            model_name='stage',
            name='dateDebut',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='uniteEnseignement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.UniteEnseignement', verbose_name="Unité d'enseignement"),
        ),
    ]
