# Generated by Django 2.0.4 on 2018-06-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0014_auto_20180613_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='credits',
            field=models.IntegerField(verbose_name='Crédits'),
        ),
    ]
