# Generated by Django 2.0.4 on 2018-06-13 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0015_auto_20180613_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='niveau',
        ),
        migrations.AddField(
            model_name='uniteenseignement',
            name='niveau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Classe'),
        ),
    ]
