# Generated by Django 2.0.4 on 2018-06-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0016_auto_20180613_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='code',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='nom_matiere',
            field=models.CharField(max_length=100, verbose_name='Nom de la matière'),
        ),
        migrations.AlterField(
            model_name='uniteenseignement',
            name='nom_unite',
            field=models.CharField(max_length=100, verbose_name="Unité d'enseignement"),
        ),
    ]
