# Generated by Django 2.0.4 on 2018-06-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0017_auto_20180613_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_semestre', models.CharField(max_length=15, unique=True, verbose_name='Semestre')),
            ],
        ),
    ]
