# Generated by Django 2.0.4 on 2018-06-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0018_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestre',
            name='niveau',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Classe'),
        ),
    ]
