# Generated by Django 2.0.4 on 2018-06-13 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0019_semestre_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniteenseignement',
            name='semestre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Semestre'),
        ),
    ]
