# Generated by Django 2.0.4 on 2018-06-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0020_uniteenseignement_semestre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matiere',
            name='code',
        ),
        migrations.AddField(
            model_name='uniteenseignement',
            name='code',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
