# Generated by Django 2.0.4 on 2018-06-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0021_auto_20180613_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniteenseignement',
            name='code',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
