# Generated by Django 2.0.4 on 2018-06-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0022_auto_20180613_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniteenseignement',
            name='niveau',
        ),
    ]
