# Generated by Django 2.0.4 on 2018-06-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0023_remove_uniteenseignement_niveau'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matiere',
            old_name='uniteEnseignement',
            new_name='ue',
        ),
    ]
