# Generated by Django 2.0.4 on 2018-06-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0024_auto_20180613_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='dateDebut',
            field=models.DateField(null=True, verbose_name='Date de début du stage'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='etat',
            field=models.CharField(choices=[('Pas encore trouvé', 'Pas encore trouvé'), ('Débuté', 'Débuté'), ('Encours', 'Encours'), ('Non trouvés', 'Non trouvé'), ('Fini', 'Fini')], max_length=20, verbose_name='État'),
        ),
    ]
