# Generated by Django 2.0.4 on 2018-06-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0025_auto_20180620_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='jury',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='note',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='pv',
            field=models.CharField(max_length=200, null=True, verbose_name='Procès verbal'),
        ),
    ]
