# Generated by Django 2.0.4 on 2018-06-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0026_auto_20180621_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soutenance',
            name='dateEffective',
            field=models.DateField(blank=True, null=True, verbose_name='Date effective'),
        ),
    ]
