# Generated by Django 2.0.4 on 2018-06-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0027_auto_20180621_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapport',
            name='motsCle',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Mots clés'),
        ),
    ]
