# Generated by Django 2.0.4 on 2018-06-25 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0028_rapport_motscle'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='dateModif',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stage',
            name='dateDebut',
            field=models.DateField(null=True, verbose_name='Stage début le'),
        ),
    ]
