# Generated by Django 2.0.4 on 2018-06-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0029_auto_20180625_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='etat',
            field=models.CharField(choices=[('Débuté', 'Débuté'), ('Encours', 'Encours'), ('Non trouvés', 'Non trouvé'), ('Fini', 'Fini')], max_length=20, verbose_name='État'),
        ),
    ]
