# Generated by Django 2.0.4 on 2018-06-29 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0030_auto_20180626_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='stage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Stage'),
        ),
    ]
