# Generated by Django 2.0.4 on 2018-07-17 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rapport', '0031_auto_20180629_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='compteUser',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
