# Generated by Django 2.0.4 on 2018-07-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0032_etudiant_compteuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='proprietaire',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='compteUser',
            new_name='compte',
        ),
        migrations.DeleteModel(
            name='Compte',
        ),
    ]
