# Generated by Django 2.0.4 on 2018-07-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0033_auto_20180718_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
