# Generated by Django 2.0.4 on 2018-07-20 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0034_etudiant_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='email',
        ),
    ]
