# Generated by Django 2.1.1 on 2018-10-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0035_remove_etudiant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='nom',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='numTel',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='prenom',
            field=models.CharField(blank=True, max_length=30, verbose_name='Prénom'),
        ),
    ]
