# Generated by Django 2.1.1 on 2018-10-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0037_auto_20181007_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Naissance'),
        ),
    ]
