# Generated by Django 2.1.1 on 2018-10-11 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0038_auto_20181011_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='dateNaissance',
        ),
    ]
