# Generated by Django 2.1.1 on 2018-10-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0039_remove_etudiant_datenaissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Naissance'),
        ),
    ]
