# Generated by Django 2.1.1 on 2018-10-18 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0041_auto_20181018_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Etudiant'),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='rapport',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Rapport'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='stagiaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Etudiant'),
        ),
    ]
