# Generated by Django 2.1.3 on 2018-12-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departement',
            options={'verbose_name': 'Département'},
        ),
        migrations.AlterModelOptions(
            name='filiere',
            options={'verbose_name': 'Filière'},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'verbose_name': 'Matière'},
        ),
        migrations.AlterModelOptions(
            name='ufr',
            options={'verbose_name': 'UFR', 'verbose_name_plural': 'UFRs'},
        ),
        migrations.AlterModelOptions(
            name='uniteenseignement',
            options={'verbose_name': "Unité d'enseignement", 'verbose_name_plural': "Unités d'enseignements"},
        ),
    ]
