# Generated by Django 2.1.3 on 2018-12-09 20:11

import common.outils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationAutre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_AtAu', models.CharField(blank=True, max_length=100, null=True)),
                ('attestation_autre', models.FileField(null=True, upload_to=common.outils.chemin_sauvegarde_attestation, verbose_name='Attestation pour autre activité')),
            ],
        ),
        migrations.CreateModel(
            name='AttestationStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_AtSta', models.CharField(blank=True, max_length=100, null=True)),
                ('attestation_stage', models.FileField(null=True, upload_to=common.outils.chemin_sauvegarde_attestation, verbose_name='Attestation de stage')),
            ],
        ),
        migrations.CreateModel(
            name='AttestationTravail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_AtTra', models.CharField(blank=True, max_length=100, null=True)),
                ('attestation_travail', models.FileField(null=True, upload_to=common.outils.chemin_sauvegarde_attestation, verbose_name='Attestation de travail')),
            ],
        ),
        migrations.CreateModel(
            name='Autre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
                ('annee_autre', models.CharField(max_length=12, null=True, verbose_name='Année académique')),
                ('structure', models.CharField(max_length=100)),
                ('poste', models.CharField(max_length=200, null=True, verbose_name='Poste ocuppé')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_doc', models.CharField(choices=[("Carte nationale d'identité", "Carte nationale d'identité"), ('Passport', 'Passeport'), ('Carte de refugé', 'Carte de refugé'), ('Carte consulaire', 'Carte consulaire'), ('Autre', 'Autre')], max_length=100, null=True, verbose_name='Type du document')),
                ('numero_doc', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro du document')),
                ('lieuEtablissement', models.CharField(blank=True, max_length=100, null=True, verbose_name="Lieu d'établissement")),
                ('dateEtablissement', models.DateField(blank=True, null=True, verbose_name="Date d'établissement")),
                ('dateExpiration', models.DateField(blank=True, null=True, verbose_name="Date d'expiration")),
            ],
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('numero_dossier', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('etat_traitement', models.CharField(choices=[('attente', 'En attente du remplissage'), ('encours', 'Encours'), ('rejeté', 'Rejeté'), ('validé', 'Validé'), ('annulé', 'Annulé')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fichiers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoId', models.ImageField(blank=True, null=True, upload_to=common.outils.chemin_sauvegarde_fichier, verbose_name="Photo d'identité")),
                ('carteId_recto', models.ImageField(blank=True, null=True, upload_to=common.outils.chemin_sauvegarde_fichier, verbose_name="Carte d'identité (recto)")),
                ('carteId_verso', models.ImageField(blank=True, null=True, upload_to=common.outils.chemin_sauvegarde_fichier, verbose_name="Carte d'identité (verso)")),
                ('passport', models.ImageField(blank=True, null=True, upload_to=common.outils.chemin_sauvegarde_fichier, verbose_name='Passeport')),
                ('curriculum', models.FileField(blank=True, null=True, upload_to=common.outils.chemin_sauvegarde_fichier, verbose_name='Curriculum Vitae, (daté et signé en pdf)')),
                ('diplome_bac', models.ImageField(blank=True, null=True, upload_to=common.outils.chemin_sauvegarde_fichier, verbose_name='Votre Baccalauréat')),
                ('attestation_licence', models.FileField(blank=True, null=True, upload_to=common.outils.chemin_sauvegarde_fichier, verbose_name='Attestation de Licence')),
                ('attestation_master', models.FileField(blank=True, null=True, upload_to=common.outils.chemin_sauvegarde_fichier, verbose_name='Attestation de Master')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('Master', 'Master'), ('Doctorat', 'Doctorat')], max_length=10, null=True, verbose_name="Niveau d'étude")),
            ],
        ),
        migrations.CreateModel(
            name='Postulant',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.Personne')),
                ('lieuNaissance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de naissance')),
                ('nationalite', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité')),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Région / Etat')),
                ('pays', django_countries.fields.CountryField(max_length=2, null=True)),
                ('compte', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('documentId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot_dossier.DocumentId')),
                ('dossier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot_dossier.Dossier')),
            ],
            bases=('common.personne',),
        ),
        migrations.CreateModel(
            name='Professionnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeur', models.CharField(max_length=200, null=True)),
                ('poste', models.CharField(max_length=200, null=True)),
                ('annee_travail', models.CharField(max_length=12, null=True, verbose_name='Année académique')),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot_dossier.Postulant')),
            ],
        ),
        migrations.CreateModel(
            name='Scolaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etablissement_sco', models.CharField(max_length=200, verbose_name='Etablissement')),
                ('classe', models.CharField(max_length=20)),
                ('moyenne_ann', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Moyenne annuelle')),
                ('annee_sco', models.CharField(max_length=12, null=True, verbose_name='Années scolaire')),
                ('eleve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot_dossier.Postulant')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(max_length=200)),
                ('type_structure', models.CharField(choices=[('ONG', 'ONG'), ('Entreprise', 'Entreprise')], max_length=15, null=True, verbose_name='Type de la structure')),
                ('annee_stage', models.CharField(max_length=12, null=True, verbose_name='Année académique')),
                ('theme', models.CharField(max_length=200, verbose_name='Thème')),
                ('stagiaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot_dossier.Postulant')),
            ],
        ),
        migrations.CreateModel(
            name='Universitaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etablissement_univ', models.CharField(max_length=200, null=True, verbose_name='Etablissement')),
                ('formation', models.CharField(max_length=200)),
                ('niveau_etude', models.CharField(max_length=30)),
                ('moyenne_semestre', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Moyenne semestre')),
                ('annee_univ', models.CharField(max_length=12, null=True, verbose_name='Années universitaire')),
                ('etudiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot_dossier.Postulant')),
            ],
        ),
        migrations.CreateModel(
            name='Doctorat',
            fields=[
                ('formation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='depot_dossier.Formation')),
                ('directeur_these', models.CharField(blank=True, max_length=200, null=True, verbose_name='Directeur de thèse')),
                ('these_doctorat', models.CharField(blank=True, max_length=200, null=True, verbose_name='Thèse')),
            ],
            bases=('depot_dossier.formation',),
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('formation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='depot_dossier.Formation')),
                ('formation_master', models.CharField(max_length=200, null=True, unique=True, verbose_name='Formation master')),
            ],
            bases=('depot_dossier.formation',),
        ),
        migrations.AddField(
            model_name='postulant',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot_dossier.Formation'),
        ),
        migrations.AddField(
            model_name='formation',
            name='dpt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Departement', verbose_name='Dépatement'),
        ),
        migrations.AddField(
            model_name='formation',
            name='ufr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.UFR', verbose_name='UFR'),
        ),
        migrations.AddField(
            model_name='fichiers',
            name='postulant',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='depot_dossier.Postulant'),
        ),
        migrations.AddField(
            model_name='autre',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='depot_dossier.Postulant'),
        ),
        migrations.AddField(
            model_name='attestationtravail',
            name='emploi',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='depot_dossier.Professionnel'),
        ),
        migrations.AddField(
            model_name='attestationstage',
            name='stage',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='depot_dossier.Stage'),
        ),
        migrations.AddField(
            model_name='attestationautre',
            name='emploi',
            field=models.OneToOneField(default='0', on_delete=django.db.models.deletion.DO_NOTHING, to='depot_dossier.Autre'),
        ),
    ]
