# Generated by Django 2.1.3 on 2018-12-09 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depot_dossier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationautre',
            name='emploi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='depot_dossier.Autre'),
        ),
        migrations.AlterField(
            model_name='attestationstage',
            name='stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='depot_dossier.Stage'),
        ),
        migrations.AlterField(
            model_name='attestationtravail',
            name='emploi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='depot_dossier.Professionnel'),
        ),
        migrations.AlterField(
            model_name='fichiers',
            name='postulant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='depot_dossier.Postulant'),
        ),
    ]
