"""
Django settings for sidinfor project.

Generated by 'django-admin startproject' using Django 2.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import django_heroku


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'u4p-(6r3v$-)m@)ajph(+f&*n=aq7w7h$7^u$@$h4g=(b6@v_n'

# SECURITY WARNING: don't run with debug turned on in production!
if os.environ.get('ENV') == 'PRODUCTION':
    DEBUG = False
    ALLOWED_HOSTS = ['https://sidinfor.herokuapp.com', ]
else:
    DEBUG = True
    ALLOWED_HOSTS = ['localhost',]

LOGIN_URL = "/login_page"

# Admin
ADMINS = [('Mohamed Zeba', 'parice02@hotmail.com'),]
SERVER_EMAIL = 'parice02@hotmail.com'
DEFAULT_FROM_EMAIL = 'parice02@hotmail.com'


# Gestion e-mail
#remplacer 'dummy' par 'smtp' en production pour rées une connexion smtp, ou par 'console' pour passer par console.
if os.environ.get('ENV') == 'PRODUCTION':
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.dummy.EmailBackend'
EMAIL_SUBJECT_PREFIX = '[SIDINFOR]'
EMAIL_HOST = 'smtp-pulse.com'
EMAIL_HOST_USER ='parice02@hotmail.com'
EMAIL_HOST_PASSWORD = 'do7ibJZJRP'
EMAIL_USE_SSL = True
#EMAIL_USE_TLS = True
EMAIL_PORT = 465

if os.environ.get('ENV') == 'PRODUCTION':
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap_datepicker_plus',
    'crispy_forms',
    'django_countries',
    'phonenumber_field',
    'wkhtmltopdf',
    'depot_rapport',
    'depot_dossier',
    'common',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'depot_dossier.get_user.RequestMiddleware'
]

if os.environ.get('ENV') == 'PRODUCTION':
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'common.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'depot_rapport/templates'),
            os.path.join(BASE_DIR, 'common/templates'),
            os.path.join(BASE_DIR, 'depot_dossier/templates'),
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'common.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'sidinfor_db.sqlite3'),
    },
    #'default': {
    #    'ENGINE': 'django.db.backends.postgresql',
    #    'NAME': 'sidinfor_db',
    #    'USER':'admin',
    #    'PASSWORD': 'pass_admin',
    #    'HOST': 'localhost',
    #    'PORT': '5432',
    #}
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'FR-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Sessions

#SESSION_EXPIRE_AT_BROWSER_CLOSE = True"
SESSION_COOKIE_AGE = 24*60*60


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'depot_rapport/static/'),
    os.path.join(BASE_DIR, 'common/static/'),
    os.path.join(BASE_DIR, 'depot_dossier/static/'),
    ]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# media

MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# wkhtmltopdf

if os.name == 'nt': 'C:/Program Files/wkhtmltopdf/lib'
else: WKHTMLTOPDF_CMD ='/usr/local/bin/wkhtmltopdf'
#else: WKHTMLTOPDF_DEBUG = True

WKHTMLTOPDF_CMD_OPTIONS = { 'quiet': False}

# crispi_form
CRISPY_TEMPLATE_PACK = 'bootstrap4'

BOOTSTRAP4 = {
'include_jquery': True,
}

# phonenumber
PHONENUMBER_DB_FORMAT = 'INTERNATIONAL'
PHONENUMBER_DEFAULT_REGION = 'BF'

django_heroku.settings(locals())

