# Generated by Django 2.1.1 on 2018-09-24 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rapport', '0035_remove_etudiant_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('duree', models.IntegerField(verbose_name='Durée')),
                ('structure', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctorat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(max_length=200, verbose_name='Spécialité')),
                ('departement', models.ForeignKey(null=True, on_delete='Départemant', to='Rapport.Departement')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_doc', models.CharField(choices=[("Carte Nationale d'identité", "Carte Nationale d'identité"), ('Passport', 'Passport')], default='Passport', max_length=100)),
                ('numero', models.CharField(max_length=20, verbose_name='Numéro')),
                ('dateEtablissement', models.DateField(verbose_name="Date d'établissement")),
                ('dateExpiration', models.DateField(verbose_name="Date d'expiration")),
                ('lieuEtablissement', models.CharField(max_length=100, verbose_name="Lieu d'établissement")),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_master', models.CharField(max_length=200, verbose_name='Option')),
                ('departement', models.ForeignKey(null=True, on_delete='Département', to='Rapport.Departement')),
            ],
        ),
        migrations.CreateModel(
            name='Postulant',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Rapport.Personne')),
                ('nationalite', models.CharField(max_length=100, verbose_name='Nationalité')),
                ('ville', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100, verbose_name='Région / Etat/ Province')),
                ('pays', models.CharField(max_length=100)),
                ('codePostal', models.CharField(max_length=10)),
                ('compte', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('documentId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DepotDoc.DocumentId')),
            ],
            bases=('Rapport.personne',),
        ),
        migrations.CreateModel(
            name='Professionel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=200)),
                ('poste', models.CharField(max_length=200)),
                ('periode', models.CharField(max_length=12)),
                ('employe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DepotDoc.Postulant')),
            ],
        ),
        migrations.CreateModel(
            name='Scolaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etablissement', models.CharField(max_length=200, verbose_name='Etablissement')),
                ('classe', models.CharField(max_length=20)),
                ('moyenne_ann', models.DecimalField(decimal_places=2, max_digits=4)),
                ('annee', models.CharField(max_length=12, verbose_name='Années scolaire')),
                ('eleve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DepotDoc.Postulant')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.CharField(max_length=200)),
                ('type_structure', models.CharField(choices=[('ONG', 'ONG'), ('Entreprise', 'Entreprise')], default='Entreprise', max_length=15, verbose_name='Type de la structure')),
                ('duree', models.IntegerField(verbose_name='Durée')),
                ('theme', models.CharField(max_length=200, verbose_name='Thème')),
                ('stagiaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DepotDoc.Postulant')),
            ],
        ),
        migrations.CreateModel(
            name='Universitaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(max_length=200)),
                ('niveau_etude', models.CharField(max_length=30)),
                ('mention', models.CharField(choices=[('Echec', 'Echec'), ('Passable', 'Passable'), ('Assez Bien', 'Assez Bien'), ('Bien', 'Bien'), ('Trés Bien', 'Trés Bien')], default='Passable', max_length=20)),
                ('etudiant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DepotDoc.Postulant')),
            ],
        ),
        migrations.AddField(
            model_name='autre',
            name='employe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DepotDoc.Postulant'),
        ),
    ]
