# Generated by Django 2.1.1 on 2018-09-26 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rapport', '0035_remove_etudiant_email'),
        ('DepotDoc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.CharField(max_length=200, unique=True)),
                ('dpt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.Departement', verbose_name='Dépatement')),
                ('ufr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Rapport.UFR')),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorat',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='master',
            name='departement',
        ),
        migrations.AddField(
            model_name='postulant',
            name='dateNaissance',
            field=models.DateField(null=True, verbose_name='Date de Naissance'),
        ),
        migrations.AddField(
            model_name='postulant',
            name='lieuNaissance',
            field=models.CharField(max_length=100, null=True, verbose_name='Lieu de Naissance'),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='codePostal',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='nationalite',
            field=models.CharField(max_length=100, null=True, verbose_name='Nationalité'),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='pays',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='region',
            field=models.CharField(max_length=100, null=True, verbose_name='Région / Etat/ Province'),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='ville',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Doctorat',
        ),
        migrations.DeleteModel(
            name='Master',
        ),
    ]
