# Generated by Django 2.1.1 on 2018-09-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepotDoc', '0002_auto_20180926_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='niveau',
            field=models.CharField(choices=[('master', 'Master'), ('doctorat', 'Doctorat')], max_length=20, null=True),
        ),
    ]
