# Generated by Django 2.1.1 on 2018-09-28 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DepotDoc', '0003_formation_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pays', models.CharField(max_length=100, null=True, verbose_name='Nom')),
            ],
        ),
        migrations.AlterField(
            model_name='postulant',
            name='pays',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DepotDoc.Pays'),
        ),
    ]
