# Generated by Django 2.1.1 on 2018-09-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepotDoc', '0005_auto_20180929_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='niveau',
            field=models.CharField(choices=[('master', 'Master'), ('doctorat', 'Doctorat')], max_length=20, null=True),
        ),
    ]
