# Generated by Django 2.1.1 on 2018-09-29 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DepotDoc', '0006_auto_20180929_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulant',
            name='formation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DepotDoc.Formation'),
        ),
    ]
