# Generated by Django 2.1.1 on 2018-09-29 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DepotDoc', '0007_postulant_formation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('numero', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('etat_traitement', models.CharField(choices=[('encours', 'Encours'), ('rejete', 'Rejeté'), ('valide', 'Validé')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='documentid',
            name='dateEtablissement',
            field=models.DateField(null=True, verbose_name="Date d'établissement"),
        ),
        migrations.AlterField(
            model_name='documentid',
            name='dateExpiration',
            field=models.DateField(null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='documentid',
            name='lieuEtablissement',
            field=models.CharField(max_length=100, null=True, verbose_name="Lieu d'établissement"),
        ),
        migrations.AlterField(
            model_name='documentid',
            name='type_doc',
            field=models.CharField(choices=[("Carte Nationale d'identité", "Carte Nationale d'identité"), ('Passport', 'Passport')], default='Passport', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='postulant',
            name='dossier',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='DepotDoc.Dossier'),
        ),
    ]
