# Generated by Django 2.1.1 on 2018-10-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DepotDoc', '0009_auto_20181005_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pays',
        ),
    ]
