# Generated by Django 2.1.1 on 2018-10-07 20:42

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DepotDoc', '0010_delete_pays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulant',
            name='codePostal',
        ),
        migrations.AlterField(
            model_name='postulant',
            name='pays',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
