# Generated by Django 2.1.1 on 2018-10-07 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DepotDoc', '0011_auto_20181007_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulant',
            name='compte',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='dateNaissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='documentId',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DepotDoc.DocumentId'),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='dossier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DepotDoc.Dossier'),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='formation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='DepotDoc.Formation'),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='lieuNaissance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='nationalite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationalité'),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Région / Etat'),
        ),
        migrations.AlterField(
            model_name='postulant',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
