# Generated by Django 2.1.1 on 2018-10-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepotDoc', '0012_auto_20181007_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='dpt',
            new_name='dpts',
        ),
        migrations.RenameField(
            model_name='formation',
            old_name='ufr',
            new_name='ufrs',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='niveau',
        ),
        migrations.AddField(
            model_name='formation',
            name='niveaus',
            field=models.CharField(choices=[('master', 'Master'), ('doctorat', 'Doctorat')], max_length=20, null=True),
        ),
    ]
