# Generated by Django 2.1.1 on 2018-10-08 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DepotDoc', '0014_auto_20181008_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='dpts',
            new_name='dpt',
        ),
        migrations.RenameField(
            model_name='formation',
            old_name='niveaux',
            new_name='niveau',
        ),
        migrations.RenameField(
            model_name='formation',
            old_name='ufrs',
            new_name='ufr',
        ),
    ]
