# Generated by Django 2.1.1 on 2018-10-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepotDoc', '0015_auto_20181008_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentid',
            old_name='numero',
            new_name='numero_doc',
        ),
        migrations.AlterField(
            model_name='documentid',
            name='type_doc',
            field=models.CharField(choices=[("Carte Nationale d'identité", "Carte Nationale d'identité"), ('Passport', 'Passport'), ('Carte de refugé', 'Carte de refugé'), ('Carte consulaire', 'Carte consulaire')], default='Passport', max_length=100, null=True, verbose_name='Type du document'),
        ),
    ]
