# Generated by Django 2.1.1 on 2018-10-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DepotDoc', '0016_auto_20181010_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulant',
            name='dateNaissance',
        ),
        migrations.AlterField(
            model_name='documentid',
            name='dateEtablissement',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'établissement"),
        ),
        migrations.AlterField(
            model_name='documentid',
            name='dateExpiration',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='documentid',
            name='lieuEtablissement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Lieu d'établissement"),
        ),
        migrations.AlterField(
            model_name='documentid',
            name='numero_doc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro du document'),
        ),
        migrations.AlterField(
            model_name='documentid',
            name='type_doc',
            field=models.CharField(choices=[("Carte nationale d'identité", "Carte nationale d'identité"), ('Passport', 'Passport'), ('Carte de refugé', 'Carte de refugé'), ('Carte consulaire', 'Carte consulaire')], max_length=100, null=True, verbose_name='Type du document'),
        ),
    ]
